# Generated by Django 5.2.15 on 2026-06-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(unique=True)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('A', 'Track A'), ('B', 'Track B')], max_length=1, unique=True)),
                ('round_type', models.CharField(default='round1', max_length=10)),
                ('try_number', models.CharField(default='try1', max_length=10)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch_project.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('round1', 'Round 1 (All)'), ('round2', 'Round 2 (Top 6)')], max_length=10)),
                ('try_number', models.CharField(choices=[('try1', 'Try 1'), ('try2', 'Try 2')], max_length=10)),
                ('track', models.CharField(choices=[('A', 'Track A'), ('B', 'Track B')], max_length=1)),
                ('raw_time', models.FloatField(default=0.0)),
                ('penalties', models.IntegerField(default=0)),
                ('penalty_seconds', models.FloatField(default=2.0)),
                ('player_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='stopwatch_project.team')),
            ],
            options={
                'unique_together': {('team', 'round_type', 'try_number')},
            },
        ),
    ]
