# Generated by Django 5.2.15 on 2026-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrun',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='matchrun',
            name='penalty_seconds',
        ),
        migrations.AddField(
            model_name='matchrun',
            name='human_penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='track_damage_penalties',
            field=models.IntegerField(default=0),
        ),
    ]
